// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetGitopsRepositoryUpdateMaskArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetGitopsRepositoryUpdateMaskArgs Empty = new GetGitopsRepositoryUpdateMaskArgs();

    /**
     * The set of field mask paths.
     * 
     */
    @Import(name="paths")
    private @Nullable Output<List<String>> paths;

    /**
     * @return The set of field mask paths.
     * 
     */
    public Optional<Output<List<String>>> paths() {
        return Optional.ofNullable(this.paths);
    }

    private GetGitopsRepositoryUpdateMaskArgs() {}

    private GetGitopsRepositoryUpdateMaskArgs(GetGitopsRepositoryUpdateMaskArgs $) {
        this.paths = $.paths;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGitopsRepositoryUpdateMaskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGitopsRepositoryUpdateMaskArgs $;

        public Builder() {
            $ = new GetGitopsRepositoryUpdateMaskArgs();
        }

        public Builder(GetGitopsRepositoryUpdateMaskArgs defaults) {
            $ = new GetGitopsRepositoryUpdateMaskArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param paths The set of field mask paths.
         * 
         * @return builder
         * 
         */
        public Builder paths(@Nullable Output<List<String>> paths) {
            $.paths = paths;
            return this;
        }

        /**
         * @param paths The set of field mask paths.
         * 
         * @return builder
         * 
         */
        public Builder paths(List<String> paths) {
            return paths(Output.of(paths));
        }

        /**
         * @param paths The set of field mask paths.
         * 
         * @return builder
         * 
         */
        public Builder paths(String... paths) {
            return paths(List.of(paths));
        }

        public GetGitopsRepositoryUpdateMaskArgs build() {
            return $;
        }
    }

}
