// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.harness.platform.inputs.GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetGitopsApplicationsApplicationSpecSourceDirectoryArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetGitopsApplicationsApplicationSpecSourceDirectoryArgs Empty = new GetGitopsApplicationsApplicationSpecSourceDirectoryArgs();

    /**
     * Glob pattern to match paths against that should be explicitly excluded from being used during manifest generation.
     * 
     */
    @Import(name="exclude")
    private @Nullable Output<String> exclude;

    /**
     * @return Glob pattern to match paths against that should be explicitly excluded from being used during manifest generation.
     * 
     */
    public Optional<Output<String>> exclude() {
        return Optional.ofNullable(this.exclude);
    }

    /**
     * Glob pattern to match paths against that should be explicitly included during manifest generation.
     * 
     */
    @Import(name="include")
    private @Nullable Output<String> include;

    /**
     * @return Glob pattern to match paths against that should be explicitly included during manifest generation.
     * 
     */
    public Optional<Output<String>> include() {
        return Optional.ofNullable(this.include);
    }

    /**
     * Options specific to applications of type Jsonnet.
     * 
     */
    @Import(name="jsonnets")
    private @Nullable Output<List<GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs>> jsonnets;

    /**
     * @return Options specific to applications of type Jsonnet.
     * 
     */
    public Optional<Output<List<GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs>>> jsonnets() {
        return Optional.ofNullable(this.jsonnets);
    }

    /**
     * Indicates to scan a directory recursively for manifests.
     * 
     */
    @Import(name="recurse")
    private @Nullable Output<Boolean> recurse;

    /**
     * @return Indicates to scan a directory recursively for manifests.
     * 
     */
    public Optional<Output<Boolean>> recurse() {
        return Optional.ofNullable(this.recurse);
    }

    private GetGitopsApplicationsApplicationSpecSourceDirectoryArgs() {}

    private GetGitopsApplicationsApplicationSpecSourceDirectoryArgs(GetGitopsApplicationsApplicationSpecSourceDirectoryArgs $) {
        this.exclude = $.exclude;
        this.include = $.include;
        this.jsonnets = $.jsonnets;
        this.recurse = $.recurse;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGitopsApplicationsApplicationSpecSourceDirectoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGitopsApplicationsApplicationSpecSourceDirectoryArgs $;

        public Builder() {
            $ = new GetGitopsApplicationsApplicationSpecSourceDirectoryArgs();
        }

        public Builder(GetGitopsApplicationsApplicationSpecSourceDirectoryArgs defaults) {
            $ = new GetGitopsApplicationsApplicationSpecSourceDirectoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param exclude Glob pattern to match paths against that should be explicitly excluded from being used during manifest generation.
         * 
         * @return builder
         * 
         */
        public Builder exclude(@Nullable Output<String> exclude) {
            $.exclude = exclude;
            return this;
        }

        /**
         * @param exclude Glob pattern to match paths against that should be explicitly excluded from being used during manifest generation.
         * 
         * @return builder
         * 
         */
        public Builder exclude(String exclude) {
            return exclude(Output.of(exclude));
        }

        /**
         * @param include Glob pattern to match paths against that should be explicitly included during manifest generation.
         * 
         * @return builder
         * 
         */
        public Builder include(@Nullable Output<String> include) {
            $.include = include;
            return this;
        }

        /**
         * @param include Glob pattern to match paths against that should be explicitly included during manifest generation.
         * 
         * @return builder
         * 
         */
        public Builder include(String include) {
            return include(Output.of(include));
        }

        /**
         * @param jsonnets Options specific to applications of type Jsonnet.
         * 
         * @return builder
         * 
         */
        public Builder jsonnets(@Nullable Output<List<GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs>> jsonnets) {
            $.jsonnets = jsonnets;
            return this;
        }

        /**
         * @param jsonnets Options specific to applications of type Jsonnet.
         * 
         * @return builder
         * 
         */
        public Builder jsonnets(List<GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs> jsonnets) {
            return jsonnets(Output.of(jsonnets));
        }

        /**
         * @param jsonnets Options specific to applications of type Jsonnet.
         * 
         * @return builder
         * 
         */
        public Builder jsonnets(GetGitopsApplicationsApplicationSpecSourceDirectoryJsonnetArgs... jsonnets) {
            return jsonnets(List.of(jsonnets));
        }

        /**
         * @param recurse Indicates to scan a directory recursively for manifests.
         * 
         * @return builder
         * 
         */
        public Builder recurse(@Nullable Output<Boolean> recurse) {
            $.recurse = recurse;
            return this;
        }

        /**
         * @param recurse Indicates to scan a directory recursively for manifests.
         * 
         * @return builder
         * 
         */
        public Builder recurse(Boolean recurse) {
            return recurse(Output.of(recurse));
        }

        public GetGitopsApplicationsApplicationSpecSourceDirectoryArgs build() {
            return $;
        }
    }

}
