// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InputSetInputSetImportRequestArgs extends com.pulumi.resources.ResourceArgs {

    public static final InputSetInputSetImportRequestArgs Empty = new InputSetInputSetImportRequestArgs();

    /**
     * Description of the input set.
     * 
     */
    @Import(name="inputSetDescription")
    private @Nullable Output<String> inputSetDescription;

    /**
     * @return Description of the input set.
     * 
     */
    public Optional<Output<String>> inputSetDescription() {
        return Optional.ofNullable(this.inputSetDescription);
    }

    /**
     * Name of the input set.
     * 
     */
    @Import(name="inputSetName")
    private @Nullable Output<String> inputSetName;

    /**
     * @return Name of the input set.
     * 
     */
    public Optional<Output<String>> inputSetName() {
        return Optional.ofNullable(this.inputSetName);
    }

    private InputSetInputSetImportRequestArgs() {}

    private InputSetInputSetImportRequestArgs(InputSetInputSetImportRequestArgs $) {
        this.inputSetDescription = $.inputSetDescription;
        this.inputSetName = $.inputSetName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InputSetInputSetImportRequestArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InputSetInputSetImportRequestArgs $;

        public Builder() {
            $ = new InputSetInputSetImportRequestArgs();
        }

        public Builder(InputSetInputSetImportRequestArgs defaults) {
            $ = new InputSetInputSetImportRequestArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param inputSetDescription Description of the input set.
         * 
         * @return builder
         * 
         */
        public Builder inputSetDescription(@Nullable Output<String> inputSetDescription) {
            $.inputSetDescription = inputSetDescription;
            return this;
        }

        /**
         * @param inputSetDescription Description of the input set.
         * 
         * @return builder
         * 
         */
        public Builder inputSetDescription(String inputSetDescription) {
            return inputSetDescription(Output.of(inputSetDescription));
        }

        /**
         * @param inputSetName Name of the input set.
         * 
         * @return builder
         * 
         */
        public Builder inputSetName(@Nullable Output<String> inputSetName) {
            $.inputSetName = inputSetName;
            return this;
        }

        /**
         * @param inputSetName Name of the input set.
         * 
         * @return builder
         * 
         */
        public Builder inputSetName(String inputSetName) {
            return inputSetName(Output.of(inputSetName));
        }

        public InputSetInputSetImportRequestArgs build() {
            return $;
        }
    }

}
