// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Outputs
{

    [OutputType]
    public sealed class GetInfrastructureV2ResourcesRequestsResult
    {
        /// <summary>
        /// CPU quantity as a Kubernetes resource string. Example: '250m', '1'.
        /// </summary>
        public readonly string? Cpu;
        /// <summary>
        /// Memory quantity as a Kubernetes resource string. Example: '256Mi', '1Gi'.
        /// </summary>
        public readonly string? Memory;

        [OutputConstructor]
        private GetInfrastructureV2ResourcesRequestsResult(
            string? cpu,

            string? memory)
        {
            Cpu = cpu;
            Memory = memory;
        }
    }
}
