// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Outputs
{

    [OutputType]
    public sealed class GetSecurityGovernanceConditionFaultSpecResult
    {
        /// <summary>
        /// List of fault specifications
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSecurityGovernanceConditionFaultSpecFaultResult> Faults;
        /// <summary>
        /// Operator for the fault specification
        /// </summary>
        public readonly string Operator;

        [OutputConstructor]
        private GetSecurityGovernanceConditionFaultSpecResult(
            ImmutableArray<Outputs.GetSecurityGovernanceConditionFaultSpecFaultResult> faults,

            string @operator)
        {
            Faults = faults;
            Operator = @operator;
        }
    }
}
