// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Outputs
{

    [OutputType]
    public sealed class SecurityGovernanceConditionMachineSpec
    {
        /// <summary>
        /// Infrastructure specification
        /// </summary>
        public readonly Outputs.SecurityGovernanceConditionMachineSpecInfraSpec? InfraSpec;

        [OutputConstructor]
        private SecurityGovernanceConditionMachineSpec(Outputs.SecurityGovernanceConditionMachineSpecInfraSpec? infraSpec)
        {
            InfraSpec = infraSpec;
        }
    }
}
