// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetYamlConfigPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetYamlConfigPlainArgs Empty = new GetYamlConfigPlainArgs();

    /**
     * Unique identifier of the application. This is not required for account level resources (i.e. cloud providers, connectors, etc.).
     * 
     */
    @Import(name="appId")
    private @Nullable String appId;

    /**
     * @return Unique identifier of the application. This is not required for account level resources (i.e. cloud providers, connectors, etc.).
     * 
     */
    public Optional<String> appId() {
        return Optional.ofNullable(this.appId);
    }

    /**
     * Path to the yaml file.
     * 
     */
    @Import(name="path", required=true)
    private String path;

    /**
     * @return Path to the yaml file.
     * 
     */
    public String path() {
        return this.path;
    }

    private GetYamlConfigPlainArgs() {}

    private GetYamlConfigPlainArgs(GetYamlConfigPlainArgs $) {
        this.appId = $.appId;
        this.path = $.path;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetYamlConfigPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetYamlConfigPlainArgs $;

        public Builder() {
            $ = new GetYamlConfigPlainArgs();
        }

        public Builder(GetYamlConfigPlainArgs defaults) {
            $ = new GetYamlConfigPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param appId Unique identifier of the application. This is not required for account level resources (i.e. cloud providers, connectors, etc.).
         * 
         * @return builder
         * 
         */
        public Builder appId(@Nullable String appId) {
            $.appId = appId;
            return this;
        }

        /**
         * @param path Path to the yaml file.
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            $.path = path;
            return this;
        }

        public GetYamlConfigPlainArgs build() {
            if ($.path == null) {
                throw new MissingRequiredPropertyException("GetYamlConfigPlainArgs", "path");
            }
            return $;
        }
    }

}
