// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserGroupPermissionsAppPermissionsProvisionerArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserGroupPermissionsAppPermissionsProvisionerArgs Empty = new UserGroupPermissionsAppPermissionsProvisionerArgs();

    /**
     * The actions allowed to be performed. Valid options are CREATE, READ, UPDATE, DELETE
     * 
     */
    @Import(name="actions", required=true)
    private Output<List<String>> actions;

    /**
     * @return The actions allowed to be performed. Valid options are CREATE, READ, UPDATE, DELETE
     * 
     */
    public Output<List<String>> actions() {
        return this.actions;
    }

    /**
     * The application IDs to which the permission applies. Leave empty to apply to all applications.
     * 
     */
    @Import(name="appIds")
    private @Nullable Output<List<String>> appIds;

    /**
     * @return The application IDs to which the permission applies. Leave empty to apply to all applications.
     * 
     */
    public Optional<Output<List<String>>> appIds() {
        return Optional.ofNullable(this.appIds);
    }

    /**
     * The provisioner IDs to which the permission applies. Leave empty to apply to all provisioners.
     * 
     */
    @Import(name="provisionerIds")
    private @Nullable Output<List<String>> provisionerIds;

    /**
     * @return The provisioner IDs to which the permission applies. Leave empty to apply to all provisioners.
     * 
     */
    public Optional<Output<List<String>>> provisionerIds() {
        return Optional.ofNullable(this.provisionerIds);
    }

    private UserGroupPermissionsAppPermissionsProvisionerArgs() {}

    private UserGroupPermissionsAppPermissionsProvisionerArgs(UserGroupPermissionsAppPermissionsProvisionerArgs $) {
        this.actions = $.actions;
        this.appIds = $.appIds;
        this.provisionerIds = $.provisionerIds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserGroupPermissionsAppPermissionsProvisionerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserGroupPermissionsAppPermissionsProvisionerArgs $;

        public Builder() {
            $ = new UserGroupPermissionsAppPermissionsProvisionerArgs();
        }

        public Builder(UserGroupPermissionsAppPermissionsProvisionerArgs defaults) {
            $ = new UserGroupPermissionsAppPermissionsProvisionerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions The actions allowed to be performed. Valid options are CREATE, READ, UPDATE, DELETE
         * 
         * @return builder
         * 
         */
        public Builder actions(Output<List<String>> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions The actions allowed to be performed. Valid options are CREATE, READ, UPDATE, DELETE
         * 
         * @return builder
         * 
         */
        public Builder actions(List<String> actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param actions The actions allowed to be performed. Valid options are CREATE, READ, UPDATE, DELETE
         * 
         * @return builder
         * 
         */
        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        /**
         * @param appIds The application IDs to which the permission applies. Leave empty to apply to all applications.
         * 
         * @return builder
         * 
         */
        public Builder appIds(@Nullable Output<List<String>> appIds) {
            $.appIds = appIds;
            return this;
        }

        /**
         * @param appIds The application IDs to which the permission applies. Leave empty to apply to all applications.
         * 
         * @return builder
         * 
         */
        public Builder appIds(List<String> appIds) {
            return appIds(Output.of(appIds));
        }

        /**
         * @param appIds The application IDs to which the permission applies. Leave empty to apply to all applications.
         * 
         * @return builder
         * 
         */
        public Builder appIds(String... appIds) {
            return appIds(List.of(appIds));
        }

        /**
         * @param provisionerIds The provisioner IDs to which the permission applies. Leave empty to apply to all provisioners.
         * 
         * @return builder
         * 
         */
        public Builder provisionerIds(@Nullable Output<List<String>> provisionerIds) {
            $.provisionerIds = provisionerIds;
            return this;
        }

        /**
         * @param provisionerIds The provisioner IDs to which the permission applies. Leave empty to apply to all provisioners.
         * 
         * @return builder
         * 
         */
        public Builder provisionerIds(List<String> provisionerIds) {
            return provisionerIds(Output.of(provisionerIds));
        }

        /**
         * @param provisionerIds The provisioner IDs to which the permission applies. Leave empty to apply to all provisioners.
         * 
         * @return builder
         * 
         */
        public Builder provisionerIds(String... provisionerIds) {
            return provisionerIds(List.of(provisionerIds));
        }

        public UserGroupPermissionsAppPermissionsProvisionerArgs build() {
            if ($.actions == null) {
                throw new MissingRequiredPropertyException("UserGroupPermissionsAppPermissionsProvisionerArgs", "actions");
            }
            return $;
        }
    }

}
