// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class UserGroupLdapSettings {
    /**
     * @return The group DN of the LDAP user group.
     * 
     */
    private @Nullable String groupDn;
    /**
     * @return The group name of the LDAP user group.
     * 
     */
    private @Nullable String groupName;
    /**
     * @return The ID of the SSO provider.
     * 
     */
    private @Nullable String ssoProviderId;

    private UserGroupLdapSettings() {}
    /**
     * @return The group DN of the LDAP user group.
     * 
     */
    public Optional<String> groupDn() {
        return Optional.ofNullable(this.groupDn);
    }
    /**
     * @return The group name of the LDAP user group.
     * 
     */
    public Optional<String> groupName() {
        return Optional.ofNullable(this.groupName);
    }
    /**
     * @return The ID of the SSO provider.
     * 
     */
    public Optional<String> ssoProviderId() {
        return Optional.ofNullable(this.ssoProviderId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(UserGroupLdapSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String groupDn;
        private @Nullable String groupName;
        private @Nullable String ssoProviderId;
        public Builder() {}
        public Builder(UserGroupLdapSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.groupDn = defaults.groupDn;
    	      this.groupName = defaults.groupName;
    	      this.ssoProviderId = defaults.ssoProviderId;
        }

        @CustomType.Setter
        public Builder groupDn(@Nullable String groupDn) {
            this.groupDn = groupDn;
            return this;
        }
        @CustomType.Setter
        public Builder groupName(@Nullable String groupName) {
            this.groupName = groupName;
            return this;
        }
        @CustomType.Setter
        public Builder ssoProviderId(@Nullable String ssoProviderId) {
            this.ssoProviderId = ssoProviderId;
            return this;
        }
        public UserGroupLdapSettings build() {
            final var o = new UserGroupLdapSettings();
            o.groupDn = groupDn;
            o.groupName = groupName;
            o.ssoProviderId = ssoProviderId;
            return o;
        }
    }
}
