// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InfraProviderVersionFileArgs extends com.pulumi.resources.ResourceArgs {

    public static final InfraProviderVersionFileArgs Empty = new InfraProviderVersionFileArgs();

    /**
     * Local path to the file to upload. Required for uploading file content.
     * 
     */
    @Import(name="filePath", required=true)
    private Output<String> filePath;

    /**
     * @return Local path to the file to upload. Required for uploading file content.
     * 
     */
    public Output<String> filePath() {
        return this.filePath;
    }

    /**
     * Name of the file to upload (e.g., terraform-provider-aws*5.0.0*linux*amd64.zip). If not provided, will be derived from file*path. Use this to override the uploaded filename if it should differ from the local filename.
     * 
     */
    @Import(name="filename")
    private @Nullable Output<String> filename;

    /**
     * @return Name of the file to upload (e.g., terraform-provider-aws*5.0.0*linux*amd64.zip). If not provided, will be derived from file*path. Use this to override the uploaded filename if it should differ from the local filename.
     * 
     */
    public Optional<Output<String>> filename() {
        return Optional.ofNullable(this.filename);
    }

    /**
     * The ID of the provider.
     * 
     */
    @Import(name="providerId", required=true)
    private Output<String> providerId;

    /**
     * @return The ID of the provider.
     * 
     */
    public Output<String> providerId() {
        return this.providerId;
    }

    /**
     * Provider version number.
     * 
     */
    @Import(name="version", required=true)
    private Output<String> version;

    /**
     * @return Provider version number.
     * 
     */
    public Output<String> version() {
        return this.version;
    }

    private InfraProviderVersionFileArgs() {}

    private InfraProviderVersionFileArgs(InfraProviderVersionFileArgs $) {
        this.filePath = $.filePath;
        this.filename = $.filename;
        this.providerId = $.providerId;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InfraProviderVersionFileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InfraProviderVersionFileArgs $;

        public Builder() {
            $ = new InfraProviderVersionFileArgs();
        }

        public Builder(InfraProviderVersionFileArgs defaults) {
            $ = new InfraProviderVersionFileArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filePath Local path to the file to upload. Required for uploading file content.
         * 
         * @return builder
         * 
         */
        public Builder filePath(Output<String> filePath) {
            $.filePath = filePath;
            return this;
        }

        /**
         * @param filePath Local path to the file to upload. Required for uploading file content.
         * 
         * @return builder
         * 
         */
        public Builder filePath(String filePath) {
            return filePath(Output.of(filePath));
        }

        /**
         * @param filename Name of the file to upload (e.g., terraform-provider-aws*5.0.0*linux*amd64.zip). If not provided, will be derived from file*path. Use this to override the uploaded filename if it should differ from the local filename.
         * 
         * @return builder
         * 
         */
        public Builder filename(@Nullable Output<String> filename) {
            $.filename = filename;
            return this;
        }

        /**
         * @param filename Name of the file to upload (e.g., terraform-provider-aws*5.0.0*linux*amd64.zip). If not provided, will be derived from file*path. Use this to override the uploaded filename if it should differ from the local filename.
         * 
         * @return builder
         * 
         */
        public Builder filename(String filename) {
            return filename(Output.of(filename));
        }

        /**
         * @param providerId The ID of the provider.
         * 
         * @return builder
         * 
         */
        public Builder providerId(Output<String> providerId) {
            $.providerId = providerId;
            return this;
        }

        /**
         * @param providerId The ID of the provider.
         * 
         * @return builder
         * 
         */
        public Builder providerId(String providerId) {
            return providerId(Output.of(providerId));
        }

        /**
         * @param version Provider version number.
         * 
         * @return builder
         * 
         */
        public Builder version(Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Provider version number.
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public InfraProviderVersionFileArgs build() {
            if ($.filePath == null) {
                throw new MissingRequiredPropertyException("InfraProviderVersionFileArgs", "filePath");
            }
            if ($.providerId == null) {
                throw new MissingRequiredPropertyException("InfraProviderVersionFileArgs", "providerId");
            }
            if ($.version == null) {
                throw new MissingRequiredPropertyException("InfraProviderVersionFileArgs", "version");
            }
            return $;
        }
    }

}
