// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package harness

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PlatformApiKey struct {
	pulumi.CustomResourceState

	// Account Identifier for the Entity
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// Type of the API Key
	ApikeyType pulumi.StringOutput `pulumi:"apikeyType"`
	// Default expiration time of the Token within API Key
	DefaultTimeToExpireToken pulumi.IntPtrOutput `pulumi:"defaultTimeToExpireToken"`
	// Description of the API Key
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Identifier of the API Key
	Identifier pulumi.StringOutput `pulumi:"identifier"`
	// Name of the API Key
	Name pulumi.StringOutput `pulumi:"name"`
	// Organization Identifier for the Entity
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// Parent Entity Identifier of the API Key
	ParentId pulumi.StringOutput `pulumi:"parentId"`
	// Project Identifier for the Entity
	ProjectId pulumi.StringPtrOutput `pulumi:"projectId"`
	// Tags for the API Key
	Tags pulumi.StringMapOutput `pulumi:"tags"`
}

// NewPlatformApiKey registers a new resource with the given unique name, arguments, and options.
func NewPlatformApiKey(ctx *pulumi.Context,
	name string, args *PlatformApiKeyArgs, opts ...pulumi.ResourceOption) (*PlatformApiKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountId == nil {
		return nil, errors.New("invalid value for required argument 'AccountId'")
	}
	if args.ApikeyType == nil {
		return nil, errors.New("invalid value for required argument 'ApikeyType'")
	}
	if args.Identifier == nil {
		return nil, errors.New("invalid value for required argument 'Identifier'")
	}
	if args.ParentId == nil {
		return nil, errors.New("invalid value for required argument 'ParentId'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource PlatformApiKey
	err := ctx.RegisterResource("harness:index/platformApiKey:PlatformApiKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPlatformApiKey gets an existing PlatformApiKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPlatformApiKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PlatformApiKeyState, opts ...pulumi.ResourceOption) (*PlatformApiKey, error) {
	var resource PlatformApiKey
	err := ctx.ReadResource("harness:index/platformApiKey:PlatformApiKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PlatformApiKey resources.
type platformApiKeyState struct {
	// Account Identifier for the Entity
	AccountId *string `pulumi:"accountId"`
	// Type of the API Key
	ApikeyType *string `pulumi:"apikeyType"`
	// Default expiration time of the Token within API Key
	DefaultTimeToExpireToken *int `pulumi:"defaultTimeToExpireToken"`
	// Description of the API Key
	Description *string `pulumi:"description"`
	// Identifier of the API Key
	Identifier *string `pulumi:"identifier"`
	// Name of the API Key
	Name *string `pulumi:"name"`
	// Organization Identifier for the Entity
	OrgId *string `pulumi:"orgId"`
	// Parent Entity Identifier of the API Key
	ParentId *string `pulumi:"parentId"`
	// Project Identifier for the Entity
	ProjectId *string `pulumi:"projectId"`
	// Tags for the API Key
	Tags map[string]string `pulumi:"tags"`
}

type PlatformApiKeyState struct {
	// Account Identifier for the Entity
	AccountId pulumi.StringPtrInput
	// Type of the API Key
	ApikeyType pulumi.StringPtrInput
	// Default expiration time of the Token within API Key
	DefaultTimeToExpireToken pulumi.IntPtrInput
	// Description of the API Key
	Description pulumi.StringPtrInput
	// Identifier of the API Key
	Identifier pulumi.StringPtrInput
	// Name of the API Key
	Name pulumi.StringPtrInput
	// Organization Identifier for the Entity
	OrgId pulumi.StringPtrInput
	// Parent Entity Identifier of the API Key
	ParentId pulumi.StringPtrInput
	// Project Identifier for the Entity
	ProjectId pulumi.StringPtrInput
	// Tags for the API Key
	Tags pulumi.StringMapInput
}

func (PlatformApiKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*platformApiKeyState)(nil)).Elem()
}

type platformApiKeyArgs struct {
	// Account Identifier for the Entity
	AccountId string `pulumi:"accountId"`
	// Type of the API Key
	ApikeyType string `pulumi:"apikeyType"`
	// Default expiration time of the Token within API Key
	DefaultTimeToExpireToken *int `pulumi:"defaultTimeToExpireToken"`
	// Description of the API Key
	Description *string `pulumi:"description"`
	// Identifier of the API Key
	Identifier string `pulumi:"identifier"`
	// Name of the API Key
	Name *string `pulumi:"name"`
	// Organization Identifier for the Entity
	OrgId *string `pulumi:"orgId"`
	// Parent Entity Identifier of the API Key
	ParentId string `pulumi:"parentId"`
	// Project Identifier for the Entity
	ProjectId *string `pulumi:"projectId"`
	// Tags for the API Key
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a PlatformApiKey resource.
type PlatformApiKeyArgs struct {
	// Account Identifier for the Entity
	AccountId pulumi.StringInput
	// Type of the API Key
	ApikeyType pulumi.StringInput
	// Default expiration time of the Token within API Key
	DefaultTimeToExpireToken pulumi.IntPtrInput
	// Description of the API Key
	Description pulumi.StringPtrInput
	// Identifier of the API Key
	Identifier pulumi.StringInput
	// Name of the API Key
	Name pulumi.StringPtrInput
	// Organization Identifier for the Entity
	OrgId pulumi.StringPtrInput
	// Parent Entity Identifier of the API Key
	ParentId pulumi.StringInput
	// Project Identifier for the Entity
	ProjectId pulumi.StringPtrInput
	// Tags for the API Key
	Tags pulumi.StringMapInput
}

func (PlatformApiKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*platformApiKeyArgs)(nil)).Elem()
}

type PlatformApiKeyInput interface {
	pulumi.Input

	ToPlatformApiKeyOutput() PlatformApiKeyOutput
	ToPlatformApiKeyOutputWithContext(ctx context.Context) PlatformApiKeyOutput
}

func (*PlatformApiKey) ElementType() reflect.Type {
	return reflect.TypeOf((**PlatformApiKey)(nil)).Elem()
}

func (i *PlatformApiKey) ToPlatformApiKeyOutput() PlatformApiKeyOutput {
	return i.ToPlatformApiKeyOutputWithContext(context.Background())
}

func (i *PlatformApiKey) ToPlatformApiKeyOutputWithContext(ctx context.Context) PlatformApiKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PlatformApiKeyOutput)
}

// PlatformApiKeyArrayInput is an input type that accepts PlatformApiKeyArray and PlatformApiKeyArrayOutput values.
// You can construct a concrete instance of `PlatformApiKeyArrayInput` via:
//
//	PlatformApiKeyArray{ PlatformApiKeyArgs{...} }
type PlatformApiKeyArrayInput interface {
	pulumi.Input

	ToPlatformApiKeyArrayOutput() PlatformApiKeyArrayOutput
	ToPlatformApiKeyArrayOutputWithContext(context.Context) PlatformApiKeyArrayOutput
}

type PlatformApiKeyArray []PlatformApiKeyInput

func (PlatformApiKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PlatformApiKey)(nil)).Elem()
}

func (i PlatformApiKeyArray) ToPlatformApiKeyArrayOutput() PlatformApiKeyArrayOutput {
	return i.ToPlatformApiKeyArrayOutputWithContext(context.Background())
}

func (i PlatformApiKeyArray) ToPlatformApiKeyArrayOutputWithContext(ctx context.Context) PlatformApiKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PlatformApiKeyArrayOutput)
}

// PlatformApiKeyMapInput is an input type that accepts PlatformApiKeyMap and PlatformApiKeyMapOutput values.
// You can construct a concrete instance of `PlatformApiKeyMapInput` via:
//
//	PlatformApiKeyMap{ "key": PlatformApiKeyArgs{...} }
type PlatformApiKeyMapInput interface {
	pulumi.Input

	ToPlatformApiKeyMapOutput() PlatformApiKeyMapOutput
	ToPlatformApiKeyMapOutputWithContext(context.Context) PlatformApiKeyMapOutput
}

type PlatformApiKeyMap map[string]PlatformApiKeyInput

func (PlatformApiKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PlatformApiKey)(nil)).Elem()
}

func (i PlatformApiKeyMap) ToPlatformApiKeyMapOutput() PlatformApiKeyMapOutput {
	return i.ToPlatformApiKeyMapOutputWithContext(context.Background())
}

func (i PlatformApiKeyMap) ToPlatformApiKeyMapOutputWithContext(ctx context.Context) PlatformApiKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PlatformApiKeyMapOutput)
}

type PlatformApiKeyOutput struct{ *pulumi.OutputState }

func (PlatformApiKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PlatformApiKey)(nil)).Elem()
}

func (o PlatformApiKeyOutput) ToPlatformApiKeyOutput() PlatformApiKeyOutput {
	return o
}

func (o PlatformApiKeyOutput) ToPlatformApiKeyOutputWithContext(ctx context.Context) PlatformApiKeyOutput {
	return o
}

// Account Identifier for the Entity
func (o PlatformApiKeyOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// Type of the API Key
func (o PlatformApiKeyOutput) ApikeyType() pulumi.StringOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringOutput { return v.ApikeyType }).(pulumi.StringOutput)
}

// Default expiration time of the Token within API Key
func (o PlatformApiKeyOutput) DefaultTimeToExpireToken() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.IntPtrOutput { return v.DefaultTimeToExpireToken }).(pulumi.IntPtrOutput)
}

// Description of the API Key
func (o PlatformApiKeyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Identifier of the API Key
func (o PlatformApiKeyOutput) Identifier() pulumi.StringOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringOutput { return v.Identifier }).(pulumi.StringOutput)
}

// Name of the API Key
func (o PlatformApiKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Organization Identifier for the Entity
func (o PlatformApiKeyOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// Parent Entity Identifier of the API Key
func (o PlatformApiKeyOutput) ParentId() pulumi.StringOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringOutput { return v.ParentId }).(pulumi.StringOutput)
}

// Project Identifier for the Entity
func (o PlatformApiKeyOutput) ProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringPtrOutput { return v.ProjectId }).(pulumi.StringPtrOutput)
}

// Tags for the API Key
func (o PlatformApiKeyOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *PlatformApiKey) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

type PlatformApiKeyArrayOutput struct{ *pulumi.OutputState }

func (PlatformApiKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PlatformApiKey)(nil)).Elem()
}

func (o PlatformApiKeyArrayOutput) ToPlatformApiKeyArrayOutput() PlatformApiKeyArrayOutput {
	return o
}

func (o PlatformApiKeyArrayOutput) ToPlatformApiKeyArrayOutputWithContext(ctx context.Context) PlatformApiKeyArrayOutput {
	return o
}

func (o PlatformApiKeyArrayOutput) Index(i pulumi.IntInput) PlatformApiKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PlatformApiKey {
		return vs[0].([]*PlatformApiKey)[vs[1].(int)]
	}).(PlatformApiKeyOutput)
}

type PlatformApiKeyMapOutput struct{ *pulumi.OutputState }

func (PlatformApiKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PlatformApiKey)(nil)).Elem()
}

func (o PlatformApiKeyMapOutput) ToPlatformApiKeyMapOutput() PlatformApiKeyMapOutput {
	return o
}

func (o PlatformApiKeyMapOutput) ToPlatformApiKeyMapOutputWithContext(ctx context.Context) PlatformApiKeyMapOutput {
	return o
}

func (o PlatformApiKeyMapOutput) MapIndex(k pulumi.StringInput) PlatformApiKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PlatformApiKey {
		return vs[0].(map[string]*PlatformApiKey)[vs[1].(string)]
	}).(PlatformApiKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PlatformApiKeyInput)(nil)).Elem(), &PlatformApiKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*PlatformApiKeyArrayInput)(nil)).Elem(), PlatformApiKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PlatformApiKeyMapInput)(nil)).Elem(), PlatformApiKeyMap{})
	pulumi.RegisterOutputType(PlatformApiKeyOutput{})
	pulumi.RegisterOutputType(PlatformApiKeyArrayOutput{})
	pulumi.RegisterOutputType(PlatformApiKeyMapOutput{})
}
