// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetGcpCloudCostConnectorBillingExportSpec {
    /**
     * @return Data Set Id.
     * 
     */
    private String dataSetId;
    /**
     * @return Table Id.
     * 
     */
    private String tableId;

    private GetGcpCloudCostConnectorBillingExportSpec() {}
    /**
     * @return Data Set Id.
     * 
     */
    public String dataSetId() {
        return this.dataSetId;
    }
    /**
     * @return Table Id.
     * 
     */
    public String tableId() {
        return this.tableId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGcpCloudCostConnectorBillingExportSpec defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dataSetId;
        private String tableId;
        public Builder() {}
        public Builder(GetGcpCloudCostConnectorBillingExportSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataSetId = defaults.dataSetId;
    	      this.tableId = defaults.tableId;
        }

        @CustomType.Setter
        public Builder dataSetId(String dataSetId) {
            if (dataSetId == null) {
              throw new MissingRequiredPropertyException("GetGcpCloudCostConnectorBillingExportSpec", "dataSetId");
            }
            this.dataSetId = dataSetId;
            return this;
        }
        @CustomType.Setter
        public Builder tableId(String tableId) {
            if (tableId == null) {
              throw new MissingRequiredPropertyException("GetGcpCloudCostConnectorBillingExportSpec", "tableId");
            }
            this.tableId = tableId;
            return this;
        }
        public GetGcpCloudCostConnectorBillingExportSpec build() {
            final var _resultValue = new GetGcpCloudCostConnectorBillingExportSpec();
            _resultValue.dataSetId = dataSetId;
            _resultValue.tableId = tableId;
            return _resultValue;
        }
    }
}
