// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetRoleAssignmentsPrincipal {
    /**
     * @return Identifier.
     * 
     */
    private String identifier;
    /**
     * @return Scope level.
     * 
     */
    private String scopeLevel;
    /**
     * @return Type.
     * 
     */
    private String type;

    private GetRoleAssignmentsPrincipal() {}
    /**
     * @return Identifier.
     * 
     */
    public String identifier() {
        return this.identifier;
    }
    /**
     * @return Scope level.
     * 
     */
    public String scopeLevel() {
        return this.scopeLevel;
    }
    /**
     * @return Type.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRoleAssignmentsPrincipal defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String identifier;
        private String scopeLevel;
        private String type;
        public Builder() {}
        public Builder(GetRoleAssignmentsPrincipal defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.identifier = defaults.identifier;
    	      this.scopeLevel = defaults.scopeLevel;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder identifier(String identifier) {
            if (identifier == null) {
              throw new MissingRequiredPropertyException("GetRoleAssignmentsPrincipal", "identifier");
            }
            this.identifier = identifier;
            return this;
        }
        @CustomType.Setter
        public Builder scopeLevel(String scopeLevel) {
            if (scopeLevel == null) {
              throw new MissingRequiredPropertyException("GetRoleAssignmentsPrincipal", "scopeLevel");
            }
            this.scopeLevel = scopeLevel;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetRoleAssignmentsPrincipal", "type");
            }
            this.type = type;
            return this;
        }
        public GetRoleAssignmentsPrincipal build() {
            final var _resultValue = new GetRoleAssignmentsPrincipal();
            _resultValue.identifier = identifier;
            _resultValue.scopeLevel = scopeLevel;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
