// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.Platform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetResourceGroupResourceFilterResourceAttributeFilter {
    private String attributeName;
    private List<String> attributeValues;

    private GetResourceGroupResourceFilterResourceAttributeFilter() {}
    public String attributeName() {
        return this.attributeName;
    }
    public List<String> attributeValues() {
        return this.attributeValues;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetResourceGroupResourceFilterResourceAttributeFilter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String attributeName;
        private List<String> attributeValues;
        public Builder() {}
        public Builder(GetResourceGroupResourceFilterResourceAttributeFilter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attributeName = defaults.attributeName;
    	      this.attributeValues = defaults.attributeValues;
        }

        @CustomType.Setter
        public Builder attributeName(String attributeName) {
            this.attributeName = Objects.requireNonNull(attributeName);
            return this;
        }
        @CustomType.Setter
        public Builder attributeValues(List<String> attributeValues) {
            this.attributeValues = Objects.requireNonNull(attributeValues);
            return this;
        }
        public Builder attributeValues(String... attributeValues) {
            return attributeValues(List.of(attributeValues));
        }
        public GetResourceGroupResourceFilterResourceAttributeFilter build() {
            final var o = new GetResourceGroupResourceFilterResourceAttributeFilter();
            o.attributeName = attributeName;
            o.attributeValues = attributeValues;
            return o;
        }
    }
}
