// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.harness.platform.outputs.GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep {
    /**
     * @return A list of label selector requirements. The requirements are ANDed.
     * 
     */
    private @Nullable List<GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression> matchExpressions;
    /**
     * @return Maximum number of simultaneous Application updates in a group. Supports both integer and percentage string values (rounds down, but floored at 1 Application for &gt;0%). Default is 100%, unbounded.
     * 
     */
    private @Nullable String maxUpdate;

    private GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep() {}
    /**
     * @return A list of label selector requirements. The requirements are ANDed.
     * 
     */
    public List<GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression> matchExpressions() {
        return this.matchExpressions == null ? List.of() : this.matchExpressions;
    }
    /**
     * @return Maximum number of simultaneous Application updates in a group. Supports both integer and percentage string values (rounds down, but floored at 1 Application for &gt;0%). Default is 100%, unbounded.
     * 
     */
    public Optional<String> maxUpdate() {
        return Optional.ofNullable(this.maxUpdate);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression> matchExpressions;
        private @Nullable String maxUpdate;
        public Builder() {}
        public Builder(GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.matchExpressions = defaults.matchExpressions;
    	      this.maxUpdate = defaults.maxUpdate;
        }

        @CustomType.Setter
        public Builder matchExpressions(@Nullable List<GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression> matchExpressions) {

            this.matchExpressions = matchExpressions;
            return this;
        }
        public Builder matchExpressions(GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStepMatchExpression... matchExpressions) {
            return matchExpressions(List.of(matchExpressions));
        }
        @CustomType.Setter
        public Builder maxUpdate(@Nullable String maxUpdate) {

            this.maxUpdate = maxUpdate;
            return this;
        }
        public GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep build() {
            final var _resultValue = new GitopsApplicationsetApplicationsetSpecStrategyRollingSyncStep();
            _resultValue.matchExpressions = matchExpressions;
            _resultValue.maxUpdate = maxUpdate;
            return _resultValue;
        }
    }
}
