// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.platform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.harness.platform.outputs.ResourceGroupResourceFilterResource;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ResourceGroupResourceFilter {
    /**
     * @return Include all resource or not
     * 
     */
    private @Nullable Boolean includeAllResources;
    /**
     * @return Resources for a resource group
     * 
     */
    private @Nullable List<ResourceGroupResourceFilterResource> resources;

    private ResourceGroupResourceFilter() {}
    /**
     * @return Include all resource or not
     * 
     */
    public Optional<Boolean> includeAllResources() {
        return Optional.ofNullable(this.includeAllResources);
    }
    /**
     * @return Resources for a resource group
     * 
     */
    public List<ResourceGroupResourceFilterResource> resources() {
        return this.resources == null ? List.of() : this.resources;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourceGroupResourceFilter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean includeAllResources;
        private @Nullable List<ResourceGroupResourceFilterResource> resources;
        public Builder() {}
        public Builder(ResourceGroupResourceFilter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.includeAllResources = defaults.includeAllResources;
    	      this.resources = defaults.resources;
        }

        @CustomType.Setter
        public Builder includeAllResources(@Nullable Boolean includeAllResources) {

            this.includeAllResources = includeAllResources;
            return this;
        }
        @CustomType.Setter
        public Builder resources(@Nullable List<ResourceGroupResourceFilterResource> resources) {

            this.resources = resources;
            return this;
        }
        public Builder resources(ResourceGroupResourceFilterResource... resources) {
            return resources(List.of(resources));
        }
        public ResourceGroupResourceFilter build() {
            final var _resultValue = new ResourceGroupResourceFilter();
            _resultValue.includeAllResources = includeAllResources;
            _resultValue.resources = resources;
            return _resultValue;
        }
    }
}
