// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Outputs
{

    [OutputType]
    public sealed class GetTriggerConditionResult
    {
        /// <summary>
        /// On webhook.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetTriggerConditionOnWebhookResult> OnWebhooks;
        /// <summary>
        /// Trigger condition.
        /// </summary>
        public readonly string TriggerConditionType;

        [OutputConstructor]
        private GetTriggerConditionResult(
            ImmutableArray<Outputs.GetTriggerConditionOnWebhookResult> onWebhooks,

            string triggerConditionType)
        {
            OnWebhooks = onWebhooks;
            TriggerConditionType = triggerConditionType;
        }
    }
}
