// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Data source for retrieving information on the current Harness account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as harness from "@pulumi/harness";
 *
 * const current = harness.platform.getCurrentAccount({});
 * ```
 */
export function getCurrentAccount(args?: GetCurrentAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetCurrentAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harness:platform/getCurrentAccount:getCurrentAccount", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCurrentAccount.
 */
export interface GetCurrentAccountArgs {
    /**
     * Id of the account.
     */
    id?: string;
}

/**
 * A collection of values returned by getCurrentAccount.
 */
export interface GetCurrentAccountResult {
    /**
     * Id of the account.
     */
    readonly accountId: string;
    /**
     * The url of the Harness control plane.
     */
    readonly endpoint: string;
    /**
     * Id of the account.
     */
    readonly id?: string;
}
/**
 * Data source for retrieving information on the current Harness account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as harness from "@pulumi/harness";
 *
 * const current = harness.platform.getCurrentAccount({});
 * ```
 */
export function getCurrentAccountOutput(args?: GetCurrentAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCurrentAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harness:platform/getCurrentAccount:getCurrentAccount", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCurrentAccount.
 */
export interface GetCurrentAccountOutputArgs {
    /**
     * Id of the account.
     */
    id?: pulumi.Input<string>;
}
