// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class ElasticsearchConnectorNoAuthenticationGetArgs : global::Pulumi.ResourceArgs
    {
        public ElasticsearchConnectorNoAuthenticationGetArgs()
        {
        }
        public static new ElasticsearchConnectorNoAuthenticationGetArgs Empty => new ElasticsearchConnectorNoAuthenticationGetArgs();
    }
}
