// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class GetGitopsAgentDeployYamlArgocdSettingsInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Controls the Environment variable HELM*SECRETS*VALUES*ALLOW*PATH_TRAVERSAL to allow or deny dot-dot-slash values file paths. Disabled by default for security reasons. This config is pushed as an env variable to the repo-server.
        /// </summary>
        [Input("enableHelmPathTraversal")]
        public Input<bool>? EnableHelmPathTraversal { get; set; }

        public GetGitopsAgentDeployYamlArgocdSettingsInputArgs()
        {
        }
        public static new GetGitopsAgentDeployYamlArgocdSettingsInputArgs Empty => new GetGitopsAgentDeployYamlArgocdSettingsInputArgs();
    }
}
