// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class GetInfraVariableSetConnectorArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Connector Ref is the reference to the connector
        /// </summary>
        [Input("connectorRef", required: true)]
        public string ConnectorRef { get; set; } = null!;

        /// <summary>
        /// Type is the connector type of the connector. Supported types: aws, azure, gcp
        /// </summary>
        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        public GetInfraVariableSetConnectorArgs()
        {
        }
        public static new GetInfraVariableSetConnectorArgs Empty => new GetInfraVariableSetConnectorArgs();
    }
}
