// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("extVars")]
        private InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetExtVarGetArgs>? _extVars;

        /// <summary>
        /// List of jsonnet external variables.
        /// </summary>
        public InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetExtVarGetArgs> ExtVars
        {
            get => _extVars ?? (_extVars = new InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetExtVarGetArgs>());
            set => _extVars = value;
        }

        [Input("libs")]
        private InputList<string>? _libs;

        /// <summary>
        /// Additional library search dirs.
        /// </summary>
        public InputList<string> Libs
        {
            get => _libs ?? (_libs = new InputList<string>());
            set => _libs = value;
        }

        [Input("tlas")]
        private InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetTlaGetArgs>? _tlas;

        /// <summary>
        /// List of jsonnet top-level arguments(TLAS).
        /// </summary>
        public InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetTlaGetArgs> Tlas
        {
            get => _tlas ?? (_tlas = new InputList<Inputs.GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetTlaGetArgs>());
            set => _tlas = value;
        }

        public GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetGetArgs()
        {
        }
        public static new GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetGetArgs Empty => new GitOpsApplicationsApplicationSpecSourceDirectoryJsonnetGetArgs();
    }
}
