// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class GitopsProjectProjectSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterResourceWhitelists")]
        private InputList<Inputs.GitopsProjectProjectSpecClusterResourceWhitelistArgs>? _clusterResourceWhitelists;

        /// <summary>
        /// ClusterResourceWhitelist contains list of whitelisted cluster level resources.
        /// </summary>
        public InputList<Inputs.GitopsProjectProjectSpecClusterResourceWhitelistArgs> ClusterResourceWhitelists
        {
            get => _clusterResourceWhitelists ?? (_clusterResourceWhitelists = new InputList<Inputs.GitopsProjectProjectSpecClusterResourceWhitelistArgs>());
            set => _clusterResourceWhitelists = value;
        }

        [Input("destinations")]
        private InputList<Inputs.GitopsProjectProjectSpecDestinationArgs>? _destinations;

        /// <summary>
        /// Destinations contains list of destinations available for deployment.
        /// </summary>
        public InputList<Inputs.GitopsProjectProjectSpecDestinationArgs> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<Inputs.GitopsProjectProjectSpecDestinationArgs>());
            set => _destinations = value;
        }

        [Input("sourceRepos")]
        private InputList<string>? _sourceRepos;

        /// <summary>
        /// SourceRepos contains list of repository URLs which can be used for deployment.
        /// </summary>
        public InputList<string> SourceRepos
        {
            get => _sourceRepos ?? (_sourceRepos = new InputList<string>());
            set => _sourceRepos = value;
        }

        public GitopsProjectProjectSpecArgs()
        {
        }
        public static new GitopsProjectProjectSpecArgs Empty => new GitopsProjectProjectSpecArgs();
    }
}
