// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Inputs
{

    public sealed class IdpScorecardCheckGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the referenced check is custom.
        /// </summary>
        [Input("custom", required: true)]
        public Input<bool> Custom { get; set; } = null!;

        /// <summary>
        /// Description of the check.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Identifier of the check.
        /// </summary>
        [Input("identifier", required: true)]
        public Input<string> Identifier { get; set; } = null!;

        /// <summary>
        /// Name of the check.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Weightage of the check when using CUSTOM.
        /// </summary>
        [Input("weightage")]
        public Input<double>? Weightage { get; set; }

        public IdpScorecardCheckGetArgs()
        {
        }
        public static new IdpScorecardCheckGetArgs Empty => new IdpScorecardCheckGetArgs();
    }
}
