// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class FaultTemplateLinkGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Link name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Link URL
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public FaultTemplateLinkGetArgs()
        {
        }
        public static new FaultTemplateLinkGetArgs Empty => new FaultTemplateLinkGetArgs();
    }
}
