// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class GetProbeTemplateHttpProbeMethodInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("gets")]
        private InputList<Inputs.GetProbeTemplateHttpProbeMethodGetInputArgs>? _gets;

        /// <summary>
        /// GET method configuration.
        /// </summary>
        public InputList<Inputs.GetProbeTemplateHttpProbeMethodGetInputArgs> Gets
        {
            get => _gets ?? (_gets = new InputList<Inputs.GetProbeTemplateHttpProbeMethodGetInputArgs>());
            set => _gets = value;
        }

        [Input("posts")]
        private InputList<Inputs.GetProbeTemplateHttpProbeMethodPostInputArgs>? _posts;

        /// <summary>
        /// POST method configuration.
        /// </summary>
        public InputList<Inputs.GetProbeTemplateHttpProbeMethodPostInputArgs> Posts
        {
            get => _posts ?? (_posts = new InputList<Inputs.GetProbeTemplateHttpProbeMethodPostInputArgs>());
            set => _posts = value;
        }

        public GetProbeTemplateHttpProbeMethodInputArgs()
        {
        }
        public static new GetProbeTemplateHttpProbeMethodInputArgs Empty => new GetProbeTemplateHttpProbeMethodInputArgs();
    }
}
