// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class ProbeTemplateRunPropertiesGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of attempts.
        /// </summary>
        [Input("attempt")]
        public Input<int>? Attempt { get; set; }

        /// <summary>
        /// Initial delay before probe execution (e.g., '5s', '1m').
        /// </summary>
        [Input("initialDelay")]
        public Input<string>? InitialDelay { get; set; }

        /// <summary>
        /// Interval between probe executions (e.g., '10s', '30s').
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        /// <summary>
        /// Polling interval for continuous probes (e.g., '2s', '5s').
        /// </summary>
        [Input("pollingInterval")]
        public Input<string>? PollingInterval { get; set; }

        /// <summary>
        /// Number of retries.
        /// </summary>
        [Input("retry")]
        public Input<int>? Retry { get; set; }

        /// <summary>
        /// Whether to stop on failure.
        /// </summary>
        [Input("stopOnFailure")]
        public Input<bool>? StopOnFailure { get; set; }

        /// <summary>
        /// Timeout for probe execution (e.g., '30s', '5m').
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        /// <summary>
        /// Verbosity level for logging.
        /// </summary>
        [Input("verbosity")]
        public Input<string>? Verbosity { get; set; }

        public ProbeTemplateRunPropertiesGetArgs()
        {
        }
        public static new ProbeTemplateRunPropertiesGetArgs Empty => new ProbeTemplateRunPropertiesGetArgs();
    }
}
