// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class ProbeTemplateK8sProbeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field selector for filtering resources.
        /// </summary>
        [Input("fieldSelector")]
        public Input<string>? FieldSelector { get; set; }

        /// <summary>
        /// API group (e.g., 'apps', 'batch').
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// Label selector for filtering resources.
        /// </summary>
        [Input("labelSelector")]
        public Input<string>? LabelSelector { get; set; }

        /// <summary>
        /// Kubernetes namespace.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Operation to perform (create, delete, present, absent, etc.).
        /// </summary>
        [Input("operation")]
        public Input<string>? Operation { get; set; }

        /// <summary>
        /// Resource type (e.g., 'pods', 'deployments').
        /// </summary>
        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        /// <summary>
        /// Comma-separated list of resource names.
        /// </summary>
        [Input("resourceNames")]
        public Input<string>? ResourceNames { get; set; }

        /// <summary>
        /// API version (e.g., 'v1', 'v1beta1').
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public ProbeTemplateK8sProbeGetArgs()
        {
        }
        public static new ProbeTemplateK8sProbeGetArgs Empty => new ProbeTemplateK8sProbeGetArgs();
    }
}
