// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class ProbeTemplateHttpProbeMethodGetMethodGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Response criteria (e.g., '==', '!=', 'contains').
        /// </summary>
        [Input("criteria")]
        public Input<string>? Criteria { get; set; }

        /// <summary>
        /// Expected response body.
        /// </summary>
        [Input("responseBody")]
        public Input<string>? ResponseBody { get; set; }

        /// <summary>
        /// Expected HTTP response code (e.g., '200', '404').
        /// </summary>
        [Input("responseCode")]
        public Input<string>? ResponseCode { get; set; }

        public ProbeTemplateHttpProbeMethodGetMethodGetArgs()
        {
        }
        public static new ProbeTemplateHttpProbeMethodGetMethodGetArgs Empty => new ProbeTemplateHttpProbeMethodGetMethodGetArgs();
    }
}
