// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Chaos.Inputs
{

    public sealed class SecurityGovernanceConditionV3MachineSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Infrastructure specification
        /// </summary>
        [Input("infraSpec")]
        public Input<Inputs.SecurityGovernanceConditionV3MachineSpecInfraSpecArgs>? InfraSpec { get; set; }

        public SecurityGovernanceConditionV3MachineSpecArgs()
        {
        }
        public static new SecurityGovernanceConditionV3MachineSpecArgs Empty => new SecurityGovernanceConditionV3MachineSpecArgs();
    }
}
