// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.fmeRuleBasedSegment;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class EnvironmentAssociationArgs extends com.pulumi.resources.ResourceArgs {

    public static final EnvironmentAssociationArgs Empty = new EnvironmentAssociationArgs();

    /**
     * JSON body for `RuleBasedSegmentDefinition` in this environment. After `EnableInEnvironment`, this is applied via update. Semantically equivalent JSON (e.g. different key order from `jsonencode` vs API refresh) is not treated as a diff.
     * 
     */
    @Import(name="definitionJson", required=true)
    private Output<String> definitionJson;

    /**
     * @return JSON body for `RuleBasedSegmentDefinition` in this environment. After `EnableInEnvironment`, this is applied via update. Semantically equivalent JSON (e.g. different key order from `jsonencode` vs API refresh) is not treated as a diff.
     * 
     */
    public Output<String> definitionJson() {
        return this.definitionJson;
    }

    /**
     * Split environment ID.
     * 
     */
    @Import(name="environmentId", required=true)
    private Output<String> environmentId;

    /**
     * @return Split environment ID.
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }

    /**
     * Harness organization identifier.
     * 
     */
    @Import(name="orgId", required=true)
    private Output<String> orgId;

    /**
     * @return Harness organization identifier.
     * 
     */
    public Output<String> orgId() {
        return this.orgId;
    }

    /**
     * Harness project identifier.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return Harness project identifier.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * Rule-based segment name (must match an existing workspace segment).
     * 
     */
    @Import(name="segmentName", required=true)
    private Output<String> segmentName;

    /**
     * @return Rule-based segment name (must match an existing workspace segment).
     * 
     */
    public Output<String> segmentName() {
        return this.segmentName;
    }

    private EnvironmentAssociationArgs() {}

    private EnvironmentAssociationArgs(EnvironmentAssociationArgs $) {
        this.definitionJson = $.definitionJson;
        this.environmentId = $.environmentId;
        this.orgId = $.orgId;
        this.projectId = $.projectId;
        this.segmentName = $.segmentName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnvironmentAssociationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnvironmentAssociationArgs $;

        public Builder() {
            $ = new EnvironmentAssociationArgs();
        }

        public Builder(EnvironmentAssociationArgs defaults) {
            $ = new EnvironmentAssociationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param definitionJson JSON body for `RuleBasedSegmentDefinition` in this environment. After `EnableInEnvironment`, this is applied via update. Semantically equivalent JSON (e.g. different key order from `jsonencode` vs API refresh) is not treated as a diff.
         * 
         * @return builder
         * 
         */
        public Builder definitionJson(Output<String> definitionJson) {
            $.definitionJson = definitionJson;
            return this;
        }

        /**
         * @param definitionJson JSON body for `RuleBasedSegmentDefinition` in this environment. After `EnableInEnvironment`, this is applied via update. Semantically equivalent JSON (e.g. different key order from `jsonencode` vs API refresh) is not treated as a diff.
         * 
         * @return builder
         * 
         */
        public Builder definitionJson(String definitionJson) {
            return definitionJson(Output.of(definitionJson));
        }

        /**
         * @param environmentId Split environment ID.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(Output<String> environmentId) {
            $.environmentId = environmentId;
            return this;
        }

        /**
         * @param environmentId Split environment ID.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(String environmentId) {
            return environmentId(Output.of(environmentId));
        }

        /**
         * @param orgId Harness organization identifier.
         * 
         * @return builder
         * 
         */
        public Builder orgId(Output<String> orgId) {
            $.orgId = orgId;
            return this;
        }

        /**
         * @param orgId Harness organization identifier.
         * 
         * @return builder
         * 
         */
        public Builder orgId(String orgId) {
            return orgId(Output.of(orgId));
        }

        /**
         * @param projectId Harness project identifier.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Harness project identifier.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param segmentName Rule-based segment name (must match an existing workspace segment).
         * 
         * @return builder
         * 
         */
        public Builder segmentName(Output<String> segmentName) {
            $.segmentName = segmentName;
            return this;
        }

        /**
         * @param segmentName Rule-based segment name (must match an existing workspace segment).
         * 
         * @return builder
         * 
         */
        public Builder segmentName(String segmentName) {
            return segmentName(Output.of(segmentName));
        }

        public EnvironmentAssociationArgs build() {
            if ($.definitionJson == null) {
                throw new MissingRequiredPropertyException("EnvironmentAssociationArgs", "definitionJson");
            }
            if ($.environmentId == null) {
                throw new MissingRequiredPropertyException("EnvironmentAssociationArgs", "environmentId");
            }
            if ($.orgId == null) {
                throw new MissingRequiredPropertyException("EnvironmentAssociationArgs", "orgId");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("EnvironmentAssociationArgs", "projectId");
            }
            if ($.segmentName == null) {
                throw new MissingRequiredPropertyException("EnvironmentAssociationArgs", "segmentName");
            }
            return $;
        }
    }

}
