# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['IdpPluginArgs', 'IdpPlugin']

@pulumi.input_type
class IdpPluginArgs:
    def __init__(__self__, *,
                 configs: pulumi.Input[_builtins.str],
                 identifier: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 env_variables: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 proxies: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]] = None):
        """
        The set of arguments for constructing a IdpPlugin resource.

        :param pulumi.Input[_builtins.str] configs: Backstage YAML configuration for the plugin.
        :param pulumi.Input[_builtins.str] identifier: Unique identifier of the plugin.
        :param pulumi.Input[_builtins.bool] enabled: Whether the plugin should be enabled. Defaults to true.
        :param pulumi.Input[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]] env_variables: Secret environment variables injected into the plugin runtime.
        :param pulumi.Input[_builtins.str] name: Display name of the plugin configuration.
        :param pulumi.Input[Sequence[pulumi.Input['IdpPluginProxyArgs']]] proxies: Delegate-based proxy configuration for outbound HTTP calls.
        """
        pulumi.set(__self__, "configs", configs)
        pulumi.set(__self__, "identifier", identifier)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if env_variables is not None:
            pulumi.set(__self__, "env_variables", env_variables)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if proxies is not None:
            pulumi.set(__self__, "proxies", proxies)

    @_builtins.property
    @pulumi.getter
    def configs(self) -> pulumi.Input[_builtins.str]:
        """
        Backstage YAML configuration for the plugin.
        """
        return pulumi.get(self, "configs")

    @configs.setter
    def configs(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "configs", value)

    @_builtins.property
    @pulumi.getter
    def identifier(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier of the plugin.
        """
        return pulumi.get(self, "identifier")

    @identifier.setter
    def identifier(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "identifier", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the plugin should be enabled. Defaults to true.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="envVariables")
    def env_variables(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]]:
        """
        Secret environment variables injected into the plugin runtime.
        """
        return pulumi.get(self, "env_variables")

    @env_variables.setter
    def env_variables(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]]):
        pulumi.set(self, "env_variables", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Display name of the plugin configuration.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def proxies(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]]:
        """
        Delegate-based proxy configuration for outbound HTTP calls.
        """
        return pulumi.get(self, "proxies")

    @proxies.setter
    def proxies(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]]):
        pulumi.set(self, "proxies", value)


@pulumi.input_type
class _IdpPluginState:
    def __init__(__self__, *,
                 configs: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 env_variables: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]] = None,
                 identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 proxies: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]] = None):
        """
        Input properties used for looking up and filtering IdpPlugin resources.

        :param pulumi.Input[_builtins.str] configs: Backstage YAML configuration for the plugin.
        :param pulumi.Input[_builtins.bool] enabled: Whether the plugin should be enabled. Defaults to true.
        :param pulumi.Input[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]] env_variables: Secret environment variables injected into the plugin runtime.
        :param pulumi.Input[_builtins.str] identifier: Unique identifier of the plugin.
        :param pulumi.Input[_builtins.str] name: Display name of the plugin configuration.
        :param pulumi.Input[Sequence[pulumi.Input['IdpPluginProxyArgs']]] proxies: Delegate-based proxy configuration for outbound HTTP calls.
        """
        if configs is not None:
            pulumi.set(__self__, "configs", configs)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if env_variables is not None:
            pulumi.set(__self__, "env_variables", env_variables)
        if identifier is not None:
            pulumi.set(__self__, "identifier", identifier)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if proxies is not None:
            pulumi.set(__self__, "proxies", proxies)

    @_builtins.property
    @pulumi.getter
    def configs(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Backstage YAML configuration for the plugin.
        """
        return pulumi.get(self, "configs")

    @configs.setter
    def configs(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "configs", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the plugin should be enabled. Defaults to true.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="envVariables")
    def env_variables(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]]:
        """
        Secret environment variables injected into the plugin runtime.
        """
        return pulumi.get(self, "env_variables")

    @env_variables.setter
    def env_variables(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginEnvVariableArgs']]]]):
        pulumi.set(self, "env_variables", value)

    @_builtins.property
    @pulumi.getter
    def identifier(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique identifier of the plugin.
        """
        return pulumi.get(self, "identifier")

    @identifier.setter
    def identifier(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "identifier", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Display name of the plugin configuration.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def proxies(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]]:
        """
        Delegate-based proxy configuration for outbound HTTP calls.
        """
        return pulumi.get(self, "proxies")

    @proxies.setter
    def proxies(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IdpPluginProxyArgs']]]]):
        pulumi.set(self, "proxies", value)


@pulumi.type_token("harness:platform/idpPlugin:IdpPlugin")
class IdpPlugin(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configs: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 env_variables: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginEnvVariableArgs', 'IdpPluginEnvVariableArgsDict']]]]] = None,
                 identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 proxies: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginProxyArgs', 'IdpPluginProxyArgsDict']]]]] = None,
                 __props__=None):
        """
        Resource for managing IDP plugin configurations.

        ## Import

        The `pulumi import` command can be used, for example:

        Import an IDP plugin by its identifier

        ```sh
        $ pulumi import harness:platform/idpPlugin:IdpPlugin example <plugin_identifier>
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] configs: Backstage YAML configuration for the plugin.
        :param pulumi.Input[_builtins.bool] enabled: Whether the plugin should be enabled. Defaults to true.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IdpPluginEnvVariableArgs', 'IdpPluginEnvVariableArgsDict']]]] env_variables: Secret environment variables injected into the plugin runtime.
        :param pulumi.Input[_builtins.str] identifier: Unique identifier of the plugin.
        :param pulumi.Input[_builtins.str] name: Display name of the plugin configuration.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IdpPluginProxyArgs', 'IdpPluginProxyArgsDict']]]] proxies: Delegate-based proxy configuration for outbound HTTP calls.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IdpPluginArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource for managing IDP plugin configurations.

        ## Import

        The `pulumi import` command can be used, for example:

        Import an IDP plugin by its identifier

        ```sh
        $ pulumi import harness:platform/idpPlugin:IdpPlugin example <plugin_identifier>
        ```


        :param str resource_name: The name of the resource.
        :param IdpPluginArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IdpPluginArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configs: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 env_variables: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginEnvVariableArgs', 'IdpPluginEnvVariableArgsDict']]]]] = None,
                 identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 proxies: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginProxyArgs', 'IdpPluginProxyArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IdpPluginArgs.__new__(IdpPluginArgs)

            if configs is None and not opts.urn:
                raise TypeError("Missing required property 'configs'")
            __props__.__dict__["configs"] = configs
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["env_variables"] = env_variables
            if identifier is None and not opts.urn:
                raise TypeError("Missing required property 'identifier'")
            __props__.__dict__["identifier"] = identifier
            __props__.__dict__["name"] = name
            __props__.__dict__["proxies"] = proxies
        super(IdpPlugin, __self__).__init__(
            'harness:platform/idpPlugin:IdpPlugin',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            configs: pulumi.Input[Optional[_builtins.str]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            env_variables: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginEnvVariableArgs', 'IdpPluginEnvVariableArgsDict']]]]] = None,
            identifier: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            proxies: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IdpPluginProxyArgs', 'IdpPluginProxyArgsDict']]]]] = None) -> 'IdpPlugin':
        """
        Get an existing IdpPlugin resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] configs: Backstage YAML configuration for the plugin.
        :param pulumi.Input[_builtins.bool] enabled: Whether the plugin should be enabled. Defaults to true.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IdpPluginEnvVariableArgs', 'IdpPluginEnvVariableArgsDict']]]] env_variables: Secret environment variables injected into the plugin runtime.
        :param pulumi.Input[_builtins.str] identifier: Unique identifier of the plugin.
        :param pulumi.Input[_builtins.str] name: Display name of the plugin configuration.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IdpPluginProxyArgs', 'IdpPluginProxyArgsDict']]]] proxies: Delegate-based proxy configuration for outbound HTTP calls.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IdpPluginState.__new__(_IdpPluginState)

        __props__.__dict__["configs"] = configs
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["env_variables"] = env_variables
        __props__.__dict__["identifier"] = identifier
        __props__.__dict__["name"] = name
        __props__.__dict__["proxies"] = proxies
        return IdpPlugin(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def configs(self) -> pulumi.Output[_builtins.str]:
        """
        Backstage YAML configuration for the plugin.
        """
        return pulumi.get(self, "configs")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the plugin should be enabled. Defaults to true.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="envVariables")
    def env_variables(self) -> pulumi.Output[Sequence['outputs.IdpPluginEnvVariable']]:
        """
        Secret environment variables injected into the plugin runtime.
        """
        return pulumi.get(self, "env_variables")

    @_builtins.property
    @pulumi.getter
    def identifier(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier of the plugin.
        """
        return pulumi.get(self, "identifier")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Display name of the plugin configuration.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def proxies(self) -> pulumi.Output[Sequence['outputs.IdpPluginProxy']]:
        """
        Delegate-based proxy configuration for outbound HTTP calls.
        """
        return pulumi.get(self, "proxies")

