// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.FmeEnvironment.Inputs
{

    public sealed class FmeEnvironmentChangePermissionsApproverArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Identifier of the user, group, or API key.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Display name (resolved by the API; may differ from the value provided at creation).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Entity type: `User`, `Group`, or `ApiKey` (a Harness service account).
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public FmeEnvironmentChangePermissionsApproverArgs()
        {
        }
        public static new FmeEnvironmentChangePermissionsApproverArgs Empty => new FmeEnvironmentChangePermissionsApproverArgs();
    }
}
