// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Outputs
{

    [OutputType]
    public sealed class GetResourceGroupResourceFilterResourceAttributeFilterResult
    {
        /// <summary>
        /// Name of the attribute
        /// </summary>
        public readonly string AttributeName;
        /// <summary>
        /// Value of the attributes
        /// </summary>
        public readonly ImmutableArray<string> AttributeValues;

        [OutputConstructor]
        private GetResourceGroupResourceFilterResourceAttributeFilterResult(
            string attributeName,

            ImmutableArray<string> attributeValues)
        {
            AttributeName = attributeName;
            AttributeValues = attributeValues;
        }
    }
}
