// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harness.Platform.Outputs
{

    [OutputType]
    public sealed class HarLifecycleRuleFilterConfig
    {
        /// <summary>
        /// Glob patterns for HuggingFace dataset names to include (HUGGINGFACE only).
        /// </summary>
        public readonly ImmutableArray<string> DatasetAllowedPatterns;
        /// <summary>
        /// Glob patterns for Maven group IDs to include (MAVEN only).
        /// </summary>
        public readonly ImmutableArray<string> GroupIdAllowedPatterns;
        /// <summary>
        /// Glob patterns for HuggingFace model names to include (HUGGINGFACE only).
        /// </summary>
        public readonly ImmutableArray<string> ModelAllowedPatterns;
        /// <summary>
        /// Glob patterns for package/image names to include.
        /// </summary>
        public readonly ImmutableArray<string> PackageNameAllowedPatterns;
        /// <summary>
        /// Package type this filter applies to (e.g. DOCKER, MAVEN, HUGGINGFACE).
        /// </summary>
        public readonly string PackageType;
        /// <summary>
        /// Glob patterns for Docker tag names to include (DOCKER only).
        /// </summary>
        public readonly ImmutableArray<string> TagNameAllowedPatterns;
        /// <summary>
        /// Glob patterns for version/tag names to include.
        /// </summary>
        public readonly ImmutableArray<string> VersionNameAllowedPatterns;

        [OutputConstructor]
        private HarLifecycleRuleFilterConfig(
            ImmutableArray<string> datasetAllowedPatterns,

            ImmutableArray<string> groupIdAllowedPatterns,

            ImmutableArray<string> modelAllowedPatterns,

            ImmutableArray<string> packageNameAllowedPatterns,

            string packageType,

            ImmutableArray<string> tagNameAllowedPatterns,

            ImmutableArray<string> versionNameAllowedPatterns)
        {
            DatasetAllowedPatterns = datasetAllowedPatterns;
            GroupIdAllowedPatterns = groupIdAllowedPatterns;
            ModelAllowedPatterns = modelAllowedPatterns;
            PackageNameAllowedPatterns = packageNameAllowedPatterns;
            PackageType = packageType;
            TagNameAllowedPatterns = tagNameAllowedPatterns;
            VersionNameAllowedPatterns = versionNameAllowedPatterns;
        }
    }
}
