// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.harness.chaos.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.harness.chaos.inputs.GetProbeTemplateHttpProbeAuth;
import com.pulumi.harness.chaos.inputs.GetProbeTemplateHttpProbeMethod;
import com.pulumi.harness.chaos.inputs.GetProbeTemplateHttpProbeTlsConfig;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetProbeTemplateHttpProbe extends com.pulumi.resources.InvokeArgs {

    public static final GetProbeTemplateHttpProbe Empty = new GetProbeTemplateHttpProbe();

    /**
     * Authentication configuration.
     * 
     */
    @Import(name="auth")
    private @Nullable GetProbeTemplateHttpProbeAuth auth;

    /**
     * @return Authentication configuration.
     * 
     */
    public Optional<GetProbeTemplateHttpProbeAuth> auth() {
        return Optional.ofNullable(this.auth);
    }

    /**
     * HTTP headers.
     * 
     */
    @Import(name="headers")
    private @Nullable Map<String,String> headers;

    /**
     * @return HTTP headers.
     * 
     */
    public Optional<Map<String,String>> headers() {
        return Optional.ofNullable(this.headers);
    }

    /**
     * HTTP method configuration with GET or POST.
     * 
     */
    @Import(name="methods")
    private @Nullable List<GetProbeTemplateHttpProbeMethod> methods;

    /**
     * @return HTTP method configuration with GET or POST.
     * 
     */
    public Optional<List<GetProbeTemplateHttpProbeMethod>> methods() {
        return Optional.ofNullable(this.methods);
    }

    /**
     * TLS configuration.
     * 
     */
    @Import(name="tlsConfig")
    private @Nullable GetProbeTemplateHttpProbeTlsConfig tlsConfig;

    /**
     * @return TLS configuration.
     * 
     */
    public Optional<GetProbeTemplateHttpProbeTlsConfig> tlsConfig() {
        return Optional.ofNullable(this.tlsConfig);
    }

    /**
     * URL to probe.
     * 
     */
    @Import(name="url", required=true)
    private String url;

    /**
     * @return URL to probe.
     * 
     */
    public String url() {
        return this.url;
    }

    private GetProbeTemplateHttpProbe() {}

    private GetProbeTemplateHttpProbe(GetProbeTemplateHttpProbe $) {
        this.auth = $.auth;
        this.headers = $.headers;
        this.methods = $.methods;
        this.tlsConfig = $.tlsConfig;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProbeTemplateHttpProbe defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProbeTemplateHttpProbe $;

        public Builder() {
            $ = new GetProbeTemplateHttpProbe();
        }

        public Builder(GetProbeTemplateHttpProbe defaults) {
            $ = new GetProbeTemplateHttpProbe(Objects.requireNonNull(defaults));
        }

        /**
         * @param auth Authentication configuration.
         * 
         * @return builder
         * 
         */
        public Builder auth(@Nullable GetProbeTemplateHttpProbeAuth auth) {
            $.auth = auth;
            return this;
        }

        /**
         * @param headers HTTP headers.
         * 
         * @return builder
         * 
         */
        public Builder headers(@Nullable Map<String,String> headers) {
            $.headers = headers;
            return this;
        }

        /**
         * @param methods HTTP method configuration with GET or POST.
         * 
         * @return builder
         * 
         */
        public Builder methods(@Nullable List<GetProbeTemplateHttpProbeMethod> methods) {
            $.methods = methods;
            return this;
        }

        /**
         * @param methods HTTP method configuration with GET or POST.
         * 
         * @return builder
         * 
         */
        public Builder methods(GetProbeTemplateHttpProbeMethod... methods) {
            return methods(List.of(methods));
        }

        /**
         * @param tlsConfig TLS configuration.
         * 
         * @return builder
         * 
         */
        public Builder tlsConfig(@Nullable GetProbeTemplateHttpProbeTlsConfig tlsConfig) {
            $.tlsConfig = tlsConfig;
            return this;
        }

        /**
         * @param url URL to probe.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            $.url = url;
            return this;
        }

        public GetProbeTemplateHttpProbe build() {
            if ($.url == null) {
                throw new MissingRequiredPropertyException("GetProbeTemplateHttpProbe", "url");
            }
            return $;
        }
    }

}
