// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Harness.Platform.Inputs
{

    public sealed class SecretSshkeySshSshkeyReferenceCredentialGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("encryptedPassphrase")]
        public Input<string>? EncryptedPassphrase { get; set; }

        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("userName", required: true)]
        public Input<string> UserName { get; set; } = null!;

        public SecretSshkeySshSshkeyReferenceCredentialGetArgs()
        {
        }
        public static new SecretSshkeySshSshkeyReferenceCredentialGetArgs Empty => new SecretSshkeySshSshkeyReferenceCredentialGetArgs();
    }
}
