// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data source for retrieving a Harness service
 */
export function getEnvironment(args: GetEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harness:index/getEnvironment:getEnvironment", {
        "appId": args.appId,
        "environmentId": args.environmentId,
        "name": args.name,
        "variableOverrides": args.variableOverrides,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentArgs {
    /**
     * The id of the application.
     */
    appId: string;
    /**
     * The id of the environment.
     */
    environmentId?: string;
    /**
     * The name of the environment.
     */
    name?: string;
    /**
     * Override for a service variable
     */
    variableOverrides?: inputs.GetEnvironmentVariableOverride[];
}

/**
 * A collection of values returned by getEnvironment.
 */
export interface GetEnvironmentResult {
    /**
     * The id of the application.
     */
    readonly appId: string;
    /**
     * The description of the environment.
     */
    readonly description: string;
    /**
     * The id of the environment.
     */
    readonly environmentId?: string;
    /**
     * The id of the environment.
     */
    readonly id: string;
    /**
     * The name of the environment.
     */
    readonly name?: string;
    /**
     * The type of the environment. Valid values are `PROD` and `NON_PROD`
     */
    readonly type: string;
    /**
     * Override for a service variable
     */
    readonly variableOverrides: outputs.GetEnvironmentVariableOverride[];
}
/**
 * Data source for retrieving a Harness service
 */
export function getEnvironmentOutput(args: GetEnvironmentOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harness:index/getEnvironment:getEnvironment", {
        "appId": args.appId,
        "environmentId": args.environmentId,
        "name": args.name,
        "variableOverrides": args.variableOverrides,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentOutputArgs {
    /**
     * The id of the application.
     */
    appId: pulumi.Input<string>;
    /**
     * The id of the environment.
     */
    environmentId?: pulumi.Input<string>;
    /**
     * The name of the environment.
     */
    name?: pulumi.Input<string>;
    /**
     * Override for a service variable
     */
    variableOverrides?: pulumi.Input<pulumi.Input<inputs.GetEnvironmentVariableOverrideArgs>[]>;
}
